version: 2.1

orbs:
  node: circleci/node@5.2.0
executors:
  pw-jammy-development:
    docker:
      - image: mcr.microsoft.com/playwright:v1.45.1-jammy

jobs:
  lint:
    executor:
      name: pw-jammy-development
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run lint
workflows:
  ci:
    jobs:
      - lint
